name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      comment:
        description: 'Comment'
        required: false
        default: ''    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build
      run: dotnet build -c Release
    - name: Pack
      run: dotnet pack -c Release -p:Version=$(date '+%Y.%m%d.%H%M') --output .
    - name: Push to nuget.org
      run: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_SECRET}} --skip-duplicate
